---
name: Build Migrator CLI

on:
  push:
    branches-ignore:
      - "l10n_master"
      - "gh-pages"
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: "util/MigratorCLI"

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: Verify Format
        run: dotnet format --verify-no-changes

  build-artifacts:
    name: Build artifacts
    runs-on: ubuntu-22.04
    needs:
      - lint
    strategy:
      fail-fast: false
      matrix:
        target:
          - osx-x64
          - linux-x64
          - win-x64

    steps:
      - name: Checkout repo
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: Print environment
        run: |
          whoami
          dotnet --info
          echo "GitHub ref: $GITHUB_REF"
          echo "GitHub event: $GITHUB_EVENT"

      - name: Restore/Clean project
        run: |
          echo "Restore"
          dotnet restore
          echo "Clean"
          dotnet clean -c "Release" -o obj/build-output/publish

      - name: Publish project
        run: dotnet publish -c "Release" -o obj/build-output/publish -r ${{ matrix.target }} --self-contained true

      - name: Upload project artifact Windows
        if: ${{ contains(matrix.target, 'win') == true }}
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
        with:
          name: MigratorCLI-${{ matrix.target }}
          path: util/MigratorCLI/obj/build-output/publish/MigratorCLI.exe
          if-no-files-found: error

      - name: Upload project artifact
        if: ${{ contains(matrix.target, 'win') == false }}
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
        with:
          name: MigratorCLI-${{ matrix.target }}
          path: util/MigratorCLI/obj/build-output/publish/MigratorCLI
          if-no-files-found: error

  check-failures:
    name: Check for failures
    if: always()
    runs-on: ubuntu-22.04
    needs:
      - lint
      - build-artifacts
    steps:
      - name: Check if any job failed
        if: |
          github.ref == 'refs/heads/master'
          || github.ref == 'refs/heads/rc'
          || github.ref == 'refs/heads/hotfix-rc'
        env:
          LINT_STATUS: ${{ needs.lint.result }}
          BUILD_ARTIFACTS_STATUS: ${{ needs.build-artifacts.result }}
        run: |
          if [ "$LINT_STATUS" = "failure" ]; then
              exit 1
          elif [ "$BUILD_ARTIFACTS_STATUS" = "failure" ]; then
              exit 1
          fi

      - name: Login to Azure - Prod Subscription
        uses: Azure/login@1f63701bf3e6892515f1b7ce2d2bf1708b46beaf
        if: failure()
        with:
          creds: ${{ secrets.AZURE_PROD_KV_CREDENTIALS }}

      - name: Retrieve secrets
        id: retrieve-secrets
        uses: bitwarden/gh-actions/get-keyvault-secrets@c3b3285993151c5af47cefcb3b9134c28ab479af
        if: failure()
        with:
          keyvault: "bitwarden-prod-kv"
          secrets: "devops-alerts-slack-webhook-url"

      - name: Notify Slack on failure
        uses: act10ns/slack@da3191ebe2e67f49b46880b4633f5591a96d1d33
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ steps.retrieve-secrets.outputs.devops-alerts-slack-webhook-url }}
        with:
          status: ${{ job.status }}
