---
name: Collect code references

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  refs:
    name: Code reference collection
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 3
      - name: Collect
        uses: launchdarkly/find-code-references@4a960c4cc0f15edc8d2548517da09546ee4967f4 # v2.11.4
        with:
          accessToken: ${{ secrets.LD_ACCESS_TOKEN }}
          projKey: Bitwarden
