---
name: Collect code references

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  refs:
    name: Code reference collection
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Collect
        uses: launchdarkly/find-code-references-in-pull-request@45fb85b5cf1a4d1186e21cac544e39eb65d502cc # v1.0.1
        with:
          project-key: default
          environment-key: dev
          access-token: ${{ secrets.LD_ACCESS_TOKEN }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
